name: gym_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.12.1
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.17.5
  camera: ^0.10.0+4
  image_picker: ^0.8.2+1
  path_provider: ^2.0.10 
  intl: ^0.20.2
  permission_handler: ^11.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
